/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FindDoctorsRouteImport } from './routes/find-doctors'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AdminDoctorsRouteImport } from './routes/admin.doctors'
import { Route as BookSymptomsRouteImport } from './routes/book.symptoms'
import { Route as DoctorsDoctorIdRouteImport } from './routes/doctors.$doctorId'
import { Route as ProviderIndexRouteImport } from './routes/provider.index'
import { Route as ProviderAppointmentsAppointmentIdRouteImport } from './routes/provider.appointments.$appointmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FindDoctorsRoute = FindDoctorsRouteImport.update({
  id: '/find-doctors',
  path: '/find-doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/admin/doctors',
  path: '/admin/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSymptomsRoute = BookSymptomsRouteImport.update({
  id: '/book/symptoms',
  path: '/book/symptoms',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsDoctorIdRoute = DoctorsDoctorIdRouteImport.update({
  id: '/doctors/$doctorId',
  path: '/doctors/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIndexRoute = ProviderIndexRouteImport.update({
  id: '/provider/',
  path: '/provider/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderAppointmentsAppointmentIdRoute =
  ProviderAppointmentsAppointmentIdRouteImport.update({
    id: '/provider/appointments/$appointmentId',
    path: '/provider/appointments/$appointmentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/find-doctors': typeof FindDoctorsRoute
  '/profile': typeof ProfileRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/book/symptoms': typeof BookSymptomsRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/provider/': typeof ProviderIndexRoute
  '/provider/appointments/$appointmentId': typeof ProviderAppointmentsAppointmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/find-doctors': typeof FindDoctorsRoute
  '/profile': typeof ProfileRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/book/symptoms': typeof BookSymptomsRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/provider': typeof ProviderIndexRoute
  '/provider/appointments/$appointmentId': typeof ProviderAppointmentsAppointmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/find-doctors': typeof FindDoctorsRoute
  '/profile': typeof ProfileRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/book/symptoms': typeof BookSymptomsRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/provider/': typeof ProviderIndexRoute
  '/provider/appointments/$appointmentId': typeof ProviderAppointmentsAppointmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/find-doctors'
    | '/profile'
    | '/admin/doctors'
    | '/book/symptoms'
    | '/doctors/$doctorId'
    | '/provider/'
    | '/provider/appointments/$appointmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/find-doctors'
    | '/profile'
    | '/admin/doctors'
    | '/book/symptoms'
    | '/doctors/$doctorId'
    | '/provider'
    | '/provider/appointments/$appointmentId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/find-doctors'
    | '/profile'
    | '/admin/doctors'
    | '/book/symptoms'
    | '/doctors/$doctorId'
    | '/provider/'
    | '/provider/appointments/$appointmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FindDoctorsRoute: typeof FindDoctorsRoute
  ProfileRoute: typeof ProfileRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  BookSymptomsRoute: typeof BookSymptomsRoute
  DoctorsDoctorIdRoute: typeof DoctorsDoctorIdRoute
  ProviderIndexRoute: typeof ProviderIndexRoute
  ProviderAppointmentsAppointmentIdRoute: typeof ProviderAppointmentsAppointmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-doctors': {
      id: '/find-doctors'
      path: '/find-doctors'
      fullPath: '/find-doctors'
      preLoaderRoute: typeof FindDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/symptoms': {
      id: '/book/symptoms'
      path: '/book/symptoms'
      fullPath: '/book/symptoms'
      preLoaderRoute: typeof BookSymptomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$doctorId': {
      id: '/doctors/$doctorId'
      path: '/doctors/$doctorId'
      fullPath: '/doctors/$doctorId'
      preLoaderRoute: typeof DoctorsDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/': {
      id: '/provider/'
      path: '/provider'
      fullPath: '/provider/'
      preLoaderRoute: typeof ProviderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/appointments/$appointmentId': {
      id: '/provider/appointments/$appointmentId'
      path: '/provider/appointments/$appointmentId'
      fullPath: '/provider/appointments/$appointmentId'
      preLoaderRoute: typeof ProviderAppointmentsAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FindDoctorsRoute: FindDoctorsRoute,
  ProfileRoute: ProfileRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  BookSymptomsRoute: BookSymptomsRoute,
  DoctorsDoctorIdRoute: DoctorsDoctorIdRoute,
  ProviderIndexRoute: ProviderIndexRoute,
  ProviderAppointmentsAppointmentIdRoute:
    ProviderAppointmentsAppointmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
